version: '3.1'

services:
  postgresDB:
    image: postgres:16.1-alpine3.19
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      # In Production - Change values
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  mongoDB:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      # In Production - Change values
      MONGO_INITDB_ROOT_USERNAME: mongoDB
      MONGO_INITDB_ROOT_PASSWORD: mongoDB